import { Request, Response } from "express"
import { Users } from "../../db/db"
// import { generateId } from "../../utils/generateId"

export const postUserController = async (req: Request, res: Response) => {
  const { nombre, apellidos, edad, email, password } = req.body
  console.log(req.body.length)
  if (req.body.length != 5) {
    throw Error("Faltan datos del usuario!")
  }
  console.log(Object.values(req.body))
  //const id = generateId() AutoGenerated id by MongoDB

  const result = await Users.create({
    nombre: nombre,
    apellidos: apellidos,
    edad: edad,
    email: email,
    password: password,
    activitats: [],
  })

  console.log(email, result)
  res.status(200).send("Se ha creado correctamente el usuario!")
}
